//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RosBiznesSoft_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class KompleksnayaAvtomatizatsiya
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KompleksnayaAvtomatizatsiya()
        {
            this.SupplySet = new HashSet<SupplySet>();
        }
    
        public int Id { get; set; }
        public string leevel { get; set; }
        public string SrokRealizatsii { get; set; }
        public Nullable<long> Price { get; set; }
        public string PO { get; set; }
        public string KolichestvoChelovek { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplySet> SupplySet { get; set; }
    }
}
