//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RosBiznesSoft_Project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RosBiznesSoftEntities : DbContext
    {
        public RosBiznesSoftEntities()
            : base("name=RosBiznesSoftEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClientsSet> ClientsSet { get; set; }
        public virtual DbSet<DelovoePO> DelovoePO { get; set; }
        public virtual DbSet<KompleksnayaAvtomatizatsiya> KompleksnayaAvtomatizatsiya { get; set; }
        public virtual DbSet<SotrudnikiSet> SotrudnikiSet { get; set; }
        public virtual DbSet<SupplySet> SupplySet { get; set; }
        public virtual DbSet<Table_1> Table_1 { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
