//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RosBiznesSoft_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class SotrudnikiSet
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Dolzhnost { get; set; }
        public string Dob { get; set; }
        public string Email { get; set; }
    }
}
