//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RosBiznesSoft_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplySet
    {
        public int Id { get; set; }
        public int IdClient { get; set; }
        public int IdTable_1 { get; set; }
        public int IdDelovoePO { get; set; }
        public int IdKompleksnayaAvtomatizasia { get; set; }
    
        public virtual ClientsSet ClientsSet { get; set; }
        public virtual DelovoePO DelovoePO { get; set; }
        public virtual KompleksnayaAvtomatizatsiya KompleksnayaAvtomatizatsiya { get; set; }
        public virtual Table_1 Table_1 { get; set; }
    }
}
