//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RosBiznesSoft_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_1()
        {
            this.SupplySet = new HashSet<SupplySet>();
        }
    
        public int Id { get; set; }
        public string NazvaniyeProgrammy { get; set; }
        public string TipZadachi { get; set; }
        public string TipObsluzhivaniya { get; set; }
        public Nullable<long> Price { get; set; }
        public int Type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplySet> SupplySet { get; set; }
    }
}
